### ISSUE TITLE
数据库连接不上

### ISSUE THREAD

**Issue by liuchongwei** [withstars/Books-Management-System#12]
(1) 编程环境为IDEA，数据库为mysql-8.0.17，JDK为10.0.2，tomcat为apache-tomcat-7.0.94
(2) book-context.xml文件中数据源定义为：
```
<bean id="dataSource" class="org.apache.commons.dbcp.BasicDataSource"
          destroy-method="close"
          p:driverClassName="com.mysql.jdbc.Driver"
          p:url="jdbc:mysql://localhost:3306/library"
          p:username="root"
          p:password=""/>
```
(3) 网页报错信息为：
> HTTP ERROR 500 <br> PWC6033: Unable to compile class for JSP <br> PWC6199: Generated servlet error: The type java.lang.Class cannot be resolved. It is indirectly referenced from required .class files <br> PWC6199: Generated servlet error: java.util.Vector cannot be resolved to a type <br> PWC6199: Generated servlet error: _jspx_dependants cannot be resolved

(4) 程序报错信息为：
```
ERROR: Compilation error
org.eclipse.jdt.internal.compiler.classfmt.ClassFormatException
        at org.eclipse.jdt.internal.compiler.classfmt.ClassFileReader.<init>(ClassFileReader.java:298)
        at org.apache.jasper.compiler.JDTJavaCompiler$1.findType(JDTJavaCompiler.java:367)
        at org.apache.jasper.compiler.JDTJavaCompiler$1.findType(JDTJavaCompiler.java:339)
        at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:119)
        at org.eclipse.jdt.internal.compiler.lookup.PackageBinding.getTypeOrPackage(PackageBinding.java:178)
        at org.eclipse.jdt.internal.compiler.lookup.Scope.getPackage(Scope.java:2149)
        at org.eclipse.jdt.internal.compiler.ast.QualifiedTypeReference.getTypeBinding(QualifiedTypeReference.java:62)
        at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:124)
        at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.resolveTypeFor(SourceTypeBinding.java:1163)
        at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.fields(SourceTypeBinding.java:630)
        at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.faultInTypesForFieldsAndMethods(SourceTypeBinding.java:616)
        at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.faultInTypes(CompilationUnitScope.java:397)
        at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:505)
        at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:329)
        at org.apache.jasper.compiler.JDTJavaCompiler.compile(JDTJavaCompiler.java:503)
        at org.apache.jasper.compiler.Compiler.generateClass(Compiler.java:368)
        at org.apache.jasper.compiler.Compiler.compile(Compiler.java:437)
        at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:608)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:360)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:486)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:380)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:440)
        at org.mortbay.jetty.servlet.Dispatcher.forward(Dispatcher.java:327)
        at org.mortbay.jetty.servlet.Dispatcher.forward(Dispatcher.java:126)
        at org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:168)
        at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303)
        at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1244)
        at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1027)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:971)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:440)
        at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:230)
        at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:926)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:410)
        at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
ERROR: Compilation error
org.eclipse.jdt.internal.compiler.classfmt.ClassFormatException
        at org.eclipse.jdt.internal.compiler.classfmt.ClassFileReader.<init>(ClassFileReader.java:298)
        at org.apache.jasper.compiler.JDTJavaCompiler$1.findType(JDTJavaCompiler.java:367)
        at org.apache.jasper.compiler.JDTJavaCompiler$1.findType(JDTJavaCompiler.java:324)
        at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:93)
        at org.eclipse.jdt.internal.compiler.lookup.UnresolvedReferenceBinding.resolve(UnresolvedReferenceBinding.java:43)
        at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.resolveType(BinaryTypeBinding.java:50)
        at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getType(LookupEnvironment.java:746)
        at org.eclipse.jdt.internal.compiler.lookup.Scope.getJavaLangClass(Scope.java:2006)
        at org.eclipse.jdt.internal.compiler.ast.ClassLiteralAccess.resolveType(ClassLiteralAccess.java:87)
        at org.eclipse.jdt.internal.compiler.ast.MessageSend.resolveType(MessageSend.java:291)
        at org.eclipse.jdt.internal.compiler.ast.CastExpression.resolveType(CastExpression.java:392)
        at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.resolve(LocalDeclaration.java:199)
        at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolveStatements(AbstractMethodDeclaration.java:418)
        at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.resolveStatements(MethodDeclaration.java:178)
        at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolve(AbstractMethodDeclaration.java:396)
        at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1072)
        at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1121)
        at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.resolve(CompilationUnitDeclaration.java:305)
        at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:512)
        at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:329)
        at org.apache.jasper.compiler.JDTJavaCompiler.compile(JDTJavaCompiler.java:503)
        at org.apache.jasper.compiler.Compiler.generateClass(Compiler.java:368)
        at org.apache.jasper.compiler.Compiler.compile(Compiler.java:437)
        at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:608)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:360)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:486)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:380)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:440)
        at org.mortbay.jetty.servlet.Dispatcher.forward(Dispatcher.java:327)
        at org.mortbay.jetty.servlet.Dispatcher.forward(Dispatcher.java:126)
        at org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:168)
        at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303)
        at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1244)
        at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1027)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:971)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:440)
        at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:230)
        at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:926)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:410)
        at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
ERROR: Error compiling file: F:\MyDocument\Project\Books-Management-System\target\work\jsp\org\apache\jsp\WEB_002dINF\jsp\index_jsp.java
[WARNING] /
org.apache.jasper.JasperException: PWC6033: Unable to compile class for JSP

PWC6199: Generated servlet error:
The type java.lang.Class cannot be resolved. It is indirectly referenced from required .class files

PWC6199: Generated servlet error:
java.util.Vector cannot be resolved to a type

PWC6199: Generated servlet error:
_jspx_dependants cannot be resolved


    at org.apache.jasper.compiler.DefaultErrorHandler.javacError (DefaultErrorHandler.java:123)
    at org.apache.jasper.compiler.ErrorDispatcher.javacError (ErrorDispatcher.java:296)
    at org.apache.jasper.compiler.Compiler.generateClass (Compiler.java:376)
    at org.apache.jasper.compiler.Compiler.compile (Compiler.java:437)
    at org.apache.jasper.JspCompilationContext.compile (JspCompilationContext.java:608)
    at org.apache.jasper.servlet.JspServletWrapper.service (JspServletWrapper.java:360)
    at org.apache.jasper.servlet.JspServlet.serviceJspFile (JspServlet.java:486)
    at org.apache.jasper.servlet.JspServlet.service (JspServlet.java:380)
    at javax.servlet.http.HttpServlet.service (HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle (ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler.handle (ServletHandler.java:390)
    at org.mortbay.jetty.security.SecurityHandler.handle (SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle (SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle (ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle (WebAppContext.java:440)
    at org.mortbay.jetty.servlet.Dispatcher.forward (Dispatcher.java:327)
    at org.mortbay.jetty.servlet.Dispatcher.forward (Dispatcher.java:126)
    at org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel (InternalResourceView.java:168)
    at org.springframework.web.servlet.view.AbstractView.render (AbstractView.java:303)
    at org.springframework.web.servlet.DispatcherServlet.render (DispatcherServlet.java:1244)
    at org.springframework.web.servlet.DispatcherServlet.processDispatchResult (DispatcherServlet.java:1027)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch (DispatcherServlet.java:971)
    at org.springframework.web.servlet.DispatcherServlet.doService (DispatcherServlet.java:893)
    at org.springframework.web.servlet.FrameworkServlet.processRequest (FrameworkServlet.java:970)
    at org.springframework.web.servlet.FrameworkServlet.doGet (FrameworkServlet.java:861)
    at javax.servlet.http.HttpServlet.service (HttpServlet.java:707)
    at org.springframework.web.servlet.FrameworkServlet.service (FrameworkServlet.java:846)
    at javax.servlet.http.HttpServlet.service (HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle (ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler.handle (ServletHandler.java:390)
    at org.mortbay.jetty.security.SecurityHandler.handle (SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle (SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle (ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle (WebAppContext.java:440)
    at org.mortbay.jetty.handler.ContextHandlerCollection.handle (ContextHandlerCollection.java:230)
    at org.mortbay.jetty.handler.HandlerCollection.handle (HandlerCollection.java:114)
    at org.mortbay.jetty.handler.HandlerWrapper.handle (HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle (Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest (HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete (HttpConnection.java:926)
    at org.mortbay.jetty.HttpParser.parseNext (HttpParser.java:549)
    at org.mortbay.jetty.HttpParser.parseAvailable (HttpParser.java:212)
    at org.mortbay.jetty.HttpConnection.handle (HttpConnection.java:404)
    at org.mortbay.io.nio.SelectChannelEndPoint.run (SelectChannelEndPoint.java:410)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run (QueuedThreadPool.java:582)
ERROR: Compilation error
org.eclipse.jdt.internal.compiler.classfmt.ClassFormatException
        at org.eclipse.jdt.internal.compiler.classfmt.ClassFileReader.<init>(ClassFileReader.java:298)
        at org.apache.jasper.compiler.JDTJavaCompiler$1.findType(JDTJavaCompiler.java:367)
        at org.apache.jasper.compiler.JDTJavaCompiler$1.findType(JDTJavaCompiler.java:339)
        at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:119)
        at org.eclipse.jdt.internal.compiler.lookup.PackageBinding.getTypeOrPackage(PackageBinding.java:178)
        at org.eclipse.jdt.internal.compiler.lookup.Scope.getPackage(Scope.java:2149)
        at org.eclipse.jdt.internal.compiler.ast.QualifiedTypeReference.getTypeBinding(QualifiedTypeReference.java:62)
        at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:124)
        at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.resolveTypeFor(SourceTypeBinding.java:1163)
        at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.fields(SourceTypeBinding.java:630)
        at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.faultInTypesForFieldsAndMethods(SourceTypeBinding.java:616)
        at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.faultInTypes(CompilationUnitScope.java:397)
        at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:505)
        at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:329)
        at org.apache.jasper.compiler.JDTJavaCompiler.compile(JDTJavaCompiler.java:503)
        at org.apache.jasper.compiler.Compiler.generateClass(Compiler.java:368)
        at org.apache.jasper.compiler.Compiler.compile(Compiler.java:437)
        at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:608)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:360)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:486)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:380)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:440)
        at org.mortbay.jetty.servlet.Dispatcher.forward(Dispatcher.java:327)
        at org.mortbay.jetty.servlet.Dispatcher.forward(Dispatcher.java:126)
        at org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:168)
        at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303)
        at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1244)
        at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1027)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:971)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:440)
        at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:230)
        at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:926)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:410)
        at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
ERROR: Error compiling file: F:\MyDocument\Project\Books-Management-System\target\work\jsp\org\apache\jsp\WEB_002dINF\jsp\_404_jsp.java
[WARNING] /favicon.ico
org.apache.jasper.JasperException: PWC6033: Unable to compile class for JSP

PWC6199: Generated servlet error:
java.util.Vector cannot be resolved to a type

PWC6199: Generated servlet error:
_jspx_dependants cannot be resolved


    at org.apache.jasper.compiler.DefaultErrorHandler.javacError (DefaultErrorHandler.java:123)
    at org.apache.jasper.compiler.ErrorDispatcher.javacError (ErrorDispatcher.java:296)
    at org.apache.jasper.compiler.Compiler.generateClass (Compiler.java:376)
    at org.apache.jasper.compiler.Compiler.compile (Compiler.java:437)
    at org.apache.jasper.JspCompilationContext.compile (JspCompilationContext.java:608)
    at org.apache.jasper.servlet.JspServletWrapper.service (JspServletWrapper.java:360)
    at org.apache.jasper.servlet.JspServlet.serviceJspFile (JspServlet.java:486)
    at org.apache.jasper.servlet.JspServlet.service (JspServlet.java:380)
    at javax.servlet.http.HttpServlet.service (HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle (ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler.handle (ServletHandler.java:390)
    at org.mortbay.jetty.security.SecurityHandler.handle (SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle (SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle (ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle (WebAppContext.java:440)
    at org.mortbay.jetty.servlet.Dispatcher.forward (Dispatcher.java:327)
    at org.mortbay.jetty.servlet.Dispatcher.forward (Dispatcher.java:126)
    at org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel (InternalResourceView.java:168)
    at org.springframework.web.servlet.view.AbstractView.render (AbstractView.java:303)
    at org.springframework.web.servlet.DispatcherServlet.render (DispatcherServlet.java:1244)
    at org.springframework.web.servlet.DispatcherServlet.processDispatchResult (DispatcherServlet.java:1027)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch (DispatcherServlet.java:971)
    at org.springframework.web.servlet.DispatcherServlet.doService (DispatcherServlet.java:893)
    at org.springframework.web.servlet.FrameworkServlet.processRequest (FrameworkServlet.java:970)
    at org.springframework.web.servlet.FrameworkServlet.doGet (FrameworkServlet.java:861)
    at javax.servlet.http.HttpServlet.service (HttpServlet.java:707)
    at org.springframework.web.servlet.FrameworkServlet.service (FrameworkServlet.java:846)
    at javax.servlet.http.HttpServlet.service (HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle (ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler.handle (ServletHandler.java:390)
    at org.mortbay.jetty.security.SecurityHandler.handle (SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle (SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle (ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle (WebAppContext.java:440)
    at org.mortbay.jetty.handler.ContextHandlerCollection.handle (ContextHandlerCollection.java:230)
    at org.mortbay.jetty.handler.HandlerCollection.handle (HandlerCollection.java:114)
    at org.mortbay.jetty.handler.HandlerWrapper.handle (HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle (Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest (HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete (HttpConnection.java:926)
    at org.mortbay.jetty.HttpParser.parseNext (HttpParser.java:549)
    at org.mortbay.jetty.HttpParser.parseAvailable (HttpParser.java:212)
    at org.mortbay.jetty.HttpConnection.handle (HttpConnection.java:404)
    at org.mortbay.io.nio.SelectChannelEndPoint.run (SelectChannelEndPoint.java:410)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run (QueuedThreadPool.java:582)
```

**Comment by liuchongwei** [comment]
自问自答一下，jetty版本问题，原本代码里的jetty不支持JDK10，所以可以将pom.xml文件中
```
<groupId>org.mortbay.jetty</groupId>
<artifactId>maven-jetty-plugin</artifactId>
<version>6.1.25</version>
```
替换为
```
<groupId>org.eclipse.jetty</groupId>
<artifactId>jetty-maven-plugin</artifactId>
<version>9.4.0.M0</version>
```
